# Generated by Django 2.2.10 on 2020-06-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200602_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CA', 'Camisa'), ('N', 'Notebook'), ('T', 'Televisão'), ('TE', 'Tênis')], max_length=2),
        ),
    ]
